# RobotFinder.com — content data. Edit here, then run: python3 _src/build.py
# Prices/specs are approximate public figures; always shown with a "verify with vendor" note.

CATEGORIES = [
  ("humanoids", "Humanoid Robots", "🤖", "General-purpose, human-shaped robots for factories, warehouses and homes."),
  ("quadrupeds", "Quadruped & Legged", "🐕", "Four-legged robots for inspection, research, security and education."),
  ("cobots", "Collaborative Robots (Cobots)", "🦾", "Safe robot arms that work next to people — machine tending, packing, welding."),
  ("industrial-arms", "Industrial Robot Arms", "🏭", "High-speed, high-payload arms for automotive, electronics and heavy industry."),
  ("warehouse-amr", "Warehouse, AMR & Logistics", "📦", "Autonomous mobile robots, picking, palletizing and truck unloading."),
  ("home-cleaning", "Home Cleaning Robots", "🧹", "Robot vacuums, mops, window and pool cleaners."),
  ("lawn-garden", "Lawn & Garden Robots", "🌱", "Robotic mowers, weeders and garden helpers."),
  ("companion", "Companion & Social Robots", "🐾", "Robot pets, home assistants and elder-care companions."),
  ("education", "Educational & STEM Kits", "🎓", "Coding robots and competition kits by age and grade."),
  ("research", "Research & ROS Platforms", "🔬", "Open, ROS-ready platforms for universities and R&D labs."),
  ("drones", "Drones & UAVs", "🚁", "Consumer, enterprise and agricultural drones."),
  ("medical", "Medical & Surgical", "🩺", "Surgical systems, rehab, pharmacy and disinfection robots."),
  ("service-delivery", "Service & Delivery", "🍽️", "Restaurant, hotel and sidewalk delivery robots."),
  ("security", "Security & Inspection", "🛡️", "Autonomous patrol, monitoring and asset inspection."),
  ("agriculture", "Agriculture Robots", "🚜", "Harvesting, weeding, spraying and livestock robots."),
  ("underwater", "Underwater & Marine", "🌊", "ROVs and AUVs for inspection, research and exploration."),
]

# (slug, name, maker, category, year, price_usd (0 = quote / not sold), status, country, market, video_id, maker_url, amazon_query, summary, specs)
ROBOTS = [
 ("boston-dynamics-spot","Spot","Boston Dynamics","quadrupeds",2020,74500,"Available","USA","business","wlkCQXHEgjA","https://bostondynamics.com/products/spot/","",
  "The benchmark industrial quadruped for autonomous inspection in plants, utilities and construction sites.",
  {"Payload":"~14 kg","Top speed":"~1.6 m/s","Runtime":"~90 min","Use cases":"Inspection, data capture, hazardous sites"}),
 ("boston-dynamics-stretch","Stretch","Boston Dynamics","warehouse-amr",2023,0,"Available","USA","business","","https://bostondynamics.com/products/stretch/","",
  "Mobile case-handling robot built to unload trucks and containers with a vacuum-gripper arm.",
  {"Max box weight":"~23 kg (50 lb)","Gripper":"Vacuum array","Base":"Omnidirectional mobile","Use cases":"Truck unloading, order building"}),
 ("boston-dynamics-atlas","Atlas (Electric)","Boston Dynamics","humanoids",2024,0,"Pilot","USA","business","29ECwExc-_M","https://bostondynamics.com/atlas/","",
  "All-electric successor to the famous hydraulic Atlas, aimed at automotive manufacturing tasks.",
  {"Actuation":"All-electric","Status":"Factory pilots","Focus":"Manufacturing / material handling"}),
 ("unitree-go2","Go2","Unitree","quadrupeds",2023,1600,"Available","China","education","","https://www.unitree.com/go2","Unitree Go2 robot dog",
  "Affordable consumer and education robot dog with 4D LiDAR — the entry point to legged robotics.",
  {"Motors":"12 joint motors","Sensing":"4D LiDAR","Starting price":"~$1,600 (Air)","Use cases":"Education, research, hobby"}),
 ("unitree-g1","G1","Unitree","humanoids",2024,16000,"Available","China","research","GzX1qOIO1bE","https://www.unitree.com/g1","",
  "The humanoid that made the category affordable — compact, agile and developer-friendly.",
  {"Height":"~1.32 m","Weight":"~35 kg","Degrees of freedom":"23–43","Starting price":"~$16,000"}),
 ("unitree-h1","H1","Unitree","humanoids",2023,90000,"Available","China","research","","https://www.unitree.com/h1","",
  "Full-size research humanoid known for speed records and dynamic motion.",
  {"Height":"~1.8 m","Weight":"~47 kg","Top speed":"~3.3 m/s","Use cases":"Research, R&D"}),
 ("unitree-r1","R1","Unitree","humanoids",2025,5900,"Pre-order","China","education","","https://www.unitree.com/","",
  "Ultra low-cost humanoid designed to put bipedal robots in classrooms and labs.",
  {"Degrees of freedom":"~24–26","Starting price":"~$5,900","Use cases":"Education, developers"}),
 ("unitree-b2","B2","Unitree","quadrupeds",2023,0,"Available","China","business","","https://www.unitree.com/b2","",
  "Heavy-duty industrial quadruped for inspection, rescue and rugged terrain.",
  {"Class":"Industrial quadruped","Use cases":"Inspection, public safety, research"}),
 ("figure-02","Figure 02","Figure AI","humanoids",2024,0,"Pilot","USA","business","0SRVJaOg9Co","https://www.figure.ai/","",
  "General-purpose humanoid tested in automotive production with onboard AI reasoning.",
  {"Height":"~1.68 m","Weight":"~70 kg","Payload":"~20 kg","Runtime":"~5 h"}),
 ("tesla-optimus","Optimus Gen 2","Tesla","humanoids",2023,0,"Not for sale","USA","business","cpraXaw7dyc","https://www.tesla.com/AI","",
  "Tesla's humanoid program targeting factory work first, consumers later.",
  {"Hands":"Tactile-sensing fingers","Gen 2 claims":"30% faster walk, 10 kg lighter","Status":"Internal development"}),
 ("agility-digit","Digit","Agility Robotics","humanoids",2023,0,"Available","USA","business","Xq_-OTQgzf0","https://www.agilityrobotics.com/","",
  "Logistics humanoid deployed in commercial warehouses, offered via Robots-as-a-Service.",
  {"Height":"~1.75 m","Payload":"~16 kg","Model":"RaaS / quote","Customers":"GXO, Schaeffler"}),
 ("1x-neo","NEO","1X","humanoids",2025,20000,"Pre-order","Norway/USA","home","","https://www.1x.tech/","",
  "Soft-bodied home humanoid built for household chores, with pre-orders opened in 2025.",
  {"Weight":"~30 kg","Pricing":"~$20,000 or monthly plan","Target":"Homes"}),
 ("universal-robots-ur5e","UR5e","Universal Robots","cobots",2018,35000,"Available","Denmark","business","","https://www.universal-robots.com/","",
  "The world's most deployed cobot class — lightweight, precise, huge accessory ecosystem.",
  {"Payload":"5 kg","Reach":"850 mm","Repeatability":"±0.03 mm","Ecosystem":"UR+ (500+ accessories)"}),
 ("universal-robots-ur20","UR20","Universal Robots","cobots",2022,0,"Available","Denmark","business","jdedvpNPg2g","https://www.universal-robots.com/","",
  "Long-reach, high-payload cobot for palletizing and heavy machine tending.",
  {"Payload":"20 kg","Reach":"1,750 mm","Use cases":"Palletizing, welding, machine tending"}),
 ("universal-robots-ur30","UR30","Universal Robots","cobots",2023,0,"Available","Denmark","business","","https://www.universal-robots.com/","",
  "Compact, strong cobot for heavy screwdriving, machine tending and material handling.",
  {"Payload":"30 kg","Reach":"1,300 mm","Use cases":"Heavy handling, screwdriving"}),
 ("standard-bots-core","Core","Standard Bots","cobots",2024,37000,"Available","USA","business","","https://standardbots.com/","",
  "US-built cobot with transparent pricing and no-code AI programming.",
  {"Payload":"18 kg","Reach":"~1,300 mm","List price":"$37,000"}),
 ("standard-bots-thor","Thor","Standard Bots","cobots",2025,49500,"Available","USA","business","","https://standardbots.com/","",
  "Heavy-payload long-reach cobot with published pricing.",
  {"Payload":"30 kg","Reach":"~2,000 mm","List price":"$49,500"}),
 ("fanuc-crx-10ia","CRX-10iA","FANUC","cobots",2019,0,"Available","Japan","business","","https://www.fanuc.com/","",
  "Rugged, easy-to-teach cobot from the world's largest industrial robot maker.",
  {"Payload":"10 kg","Reach":"~1,249 mm","Axes":"6"}),
 ("abb-yumi","YuMi IRB 14000","ABB","industrial-arms",2015,40000,"Available","Switzerland","business","","https://new.abb.com/products/robotics","",
  "Dual-arm collaborative robot for small-parts assembly and electronics.",
  {"Payload":"0.5 kg per arm","Axes":"7 per arm","Use cases":"Small-parts assembly"}),
 ("clearpath-husky","Husky UGV","Clearpath Robotics","research",2011,0,"Available","Canada","research","","https://clearpathrobotics.com/","",
  "Rugged outdoor research platform used by universities worldwide.",
  {"Payload":"~75 kg","Terrain":"Outdoor, all-weather","Software":"ROS / ROS 2"}),
 ("turtlebot-4","TurtleBot 4","Clearpath Robotics","education",2022,1200,"Available","Canada","education","","https://clearpathrobotics.com/turtlebot-4/","TurtleBot 4",
  "The standard ROS 2 learning robot for classrooms and research labs.",
  {"Software":"ROS 2","Sensors":"2D LiDAR, OAK-D camera","Starting price":"~$1,200 (Lite)"}),
 ("irobot-roomba-combo-j7","Roomba Combo j7+","iRobot","home-cleaning",2022,1100,"Available","USA","home","","https://www.irobot.com/","iRobot Roomba Combo j7+",
  "Vacuum-and-mop robot with a mop that lifts onto the top on carpet.",
  {"Type":"Vacuum + mop","Dock":"Auto-empty","Navigation":"Camera obstacle avoidance"}),
 ("roborock-s8-maxv-ultra","S8 MaxV Ultra","Roborock","home-cleaning",2024,1800,"Available","China","home","","https://www.roborock.com/","Roborock S8 MaxV Ultra",
  "Flagship vacuum-mop with self-washing, self-drying dock.",
  {"Suction":"~10,000 Pa","Dock":"Self-wash, self-empty","Navigation":"LiDAR + AI obstacle avoidance"}),
 ("husqvarna-automower-450x","Automower 450X","Husqvarna","lawn-garden",2018,3500,"Available","Sweden","home","","https://www.husqvarna.com/","Husqvarna Automower 450X",
  "Premium robotic mower for large, complex lawns with GPS navigation.",
  {"Area":"~1.25 acres","Navigation":"GPS-assisted","Control":"App + voice assistants"}),
 ("sony-aibo","aibo ERS-1000","Sony","companion",2018,2900,"Available","Japan","home","","https://us.aibo.com/","Sony aibo",
  "Sony's AI robot dog with expressive OLED eyes and a personality that learns.",
  {"Eyes":"OLED","AI":"Cloud-connected learning","Features":"Face recognition"}),
 ("amazon-astro","Astro","Amazon","companion",2021,1600,"Invite only","USA","home","","https://www.amazon.com/","Amazon Astro",
  "Home robot with a periscope camera for monitoring and Alexa on wheels.",
  {"Camera":"Periscope","Assistant":"Alexa","Use cases":"Home monitoring"}),
 ("lego-spike-prime","SPIKE Prime","LEGO Education","education",2020,400,"Available","Denmark","education","","https://education.lego.com/","LEGO Education SPIKE Prime",
  "The classroom favorite for STEM and FIRST LEGO League teams.",
  {"Coding":"Scratch & Python","Hub":"6-port","Ages":"10+"}),
 ("sphero-bolt","BOLT","Sphero","education",2018,160,"Available","USA","education","","https://sphero.com/","Sphero BOLT",
  "Programmable robot ball with an LED matrix — coding for all ages.",
  {"Display":"8×8 LED matrix","App":"Sphero Edu","Ages":"8+"}),
 ("dji-mavic-3-pro","Mavic 3 Pro","DJI","drones",2023,2199,"Available","China","home","","https://www.dji.com/","DJI Mavic 3 Pro",
  "Triple-camera flagship consumer drone for creators.",
  {"Cameras":"3","Flight time":"~43 min","Class":"Prosumer"}),
 ("dji-agras-t50","Agras T50","DJI","agriculture",2023,0,"Available","China","business","","https://ag.dji.com/","",
  "Agricultural spraying and spreading drone for large farms.",
  {"Spray payload":"~40 kg","Spread payload":"~50 kg","Use cases":"Crop spraying, seeding"}),
 ("intuitive-da-vinci-5","da Vinci 5","Intuitive","medical",2024,0,"Available","USA","business","","https://www.intuitive.com/","",
  "Next-generation multiport surgical system with force-feedback instruments.",
  {"Type":"Multiport surgical","Feature":"Force feedback","Buyer":"Hospitals"}),
 ("pudu-bellabot","BellaBot","Pudu Robotics","service-delivery",2020,15000,"Available","China","business","","https://www.pudurobotics.com/","",
  "Cat-faced restaurant delivery robot found in thousands of venues worldwide.",
  {"Trays":"4","Load":"~40 kg","Use cases":"Restaurants, hotels"}),
 ("knightscope-k5","K5","Knightscope","security",2015,0,"Available","USA","business","","https://www.knightscope.com/","",
  "Autonomous outdoor security robot offered as Machine-as-a-Service.",
  {"Video":"360°","Features":"License-plate recognition","Model":"Subscription"}),
 ("blue-robotics-bluerov2","BlueROV2","Blue Robotics","underwater",2016,4000,"Available","USA","research","","https://bluerobotics.com/","",
  "Affordable open-source ROV for inspection, research and aquaculture.",
  {"Depth rating":"~100 m","Software":"Open source","Use cases":"Inspection, research"}),
]

VIDEOS = [
 ("29ECwExc-_M","All New Atlas","Boston Dynamics","humanoids"),
 ("fn3KWM1kuAw","Do You Love Me?","Boston Dynamics","humanoids"),
 ("tF4DML7FIWk","Atlas | Partners in Parkour","Boston Dynamics","humanoids"),
 ("wlkCQXHEgjA","Spot Launch","Boston Dynamics","quadrupeds"),
 ("GzX1qOIO1bE","Unitree G1 Humanoid Agent — from $16K","Unitree Robotics","humanoids"),
 ("Nkh6RUocD8c","Unitree G1 nails the world's first kip-up","Unitree Robotics","humanoids"),
 ("0SRVJaOg9Co","Introducing Figure 02","Figure","humanoids"),
 ("cpraXaw7dyc","Optimus — Gen 2","Tesla","humanoids"),
 ("jdedvpNPg2g","UR20 Product Announcement","Universal Robots","cobots"),
 ("Xq_-OTQgzf0","Digit: GXO's human-centric robot","GXO","humanoids"),
]
